import Head from 'next/head';
import dynamic from 'next/dynamic';
import { NextPageContext } from 'next';

const RemoteApp = dynamic(() => import('remote1/pages/index'), {
  ssr: true
}) as any;
const page = import('remote1/pages/index');

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Host App</h1>
        <RemoteApp {...props} />
      </main>
    </>
  );
}
export async function getServerSideProps(context: NextPageContext) {
  const fedPage = await page;
  console.log(fedPage.getServerSideProps);
  if (fedPage.getServerSideProps) {
    console.log('asfasdfdsf');
    return fedPage.getServerSideProps(context);
  }
  return {
    props: {} // will be passed to the page component as props
  };
}
